### ISSUE TITLE
Classic left mouse button dont zoom into other maps

### ISSUE THREAD

**Issue by Axejess** [Nevcairiel/Mapster#13]
Right button works to zoom out. But when I click the right buytton to zoom in again it won't work.

also @ 3440x1440 the map is to much above the screen i had to readjust the worldframe window with moveanything to be more down. And that cause the x mark button to not be alligned at the right position as well

**Comment by Nevcairiel** [comment]
Zooming in and out works just fine here. In my experience if its broken its caused by other addons. One addon I know not playing nicely on Classic and stepping on everyone else is for example Tomcat's Tours, if you run that try disabling it and see if it improves.

The default map size should also be adequately small to fit on any screen, maybe thats a by-product of the same issue.

**Comment by Axejess** [comment]
Seems your absolutely right thought i did disabled all the minimap addons but I forgot that one. Thnx!
