### ISSUE TITLE
map scaling does work with clicking zones

### ISSUE THREAD

**Issue by shade0o** [Nevcairiel/Mapster#16]
when you scale the map (160% as i have) it doesn't let you scale where you click though to other zones as the zones outlines stay set at 100%, if you hover over a random place you may find the right zone, but its a shot in the dark

**Comment by Nevcairiel** [comment]
This bug is caused by other addons interfering with the map, when they have no business to do so. One prime candidate is for example Tomcat's Tours (which should really stick to providing information, instead of messing with the map itself), if you run that on Classic, disable or uninstall it and it should work.
