### ISSUE TITLE
Map scale affecting cursor accuracy

### ISSUE THREAD

**Issue by Failduck** [Nevcairiel/Mapster#20]
I've experienced an issue with the world map, which seems to be related to the scaling.  If the map frame's scale is set at 100%, the zone highlight and click destination for the continents is accurate.  IF the scale is moved at all, (using either the corner stretch arrow the addon settings UI) the highlight and click destination moved progressively further from the cursor.

Also, a related feature suggestion: an option to lock/unlock the corner stretch arrow on the map frame.

**Comment by Nevcairiel** [comment]
This issue is usually caused by other addons messing with the map scaling behavior. One addon I know that breaks it, for example, is Tomcat Tours, if you run that by any chance.

**Comment by Failduck** [comment]
I don't use Tomcat's in classic, but I did start noticing the error after installing HandyNotes for Classic. (and later disabled it while troubleshooting, but the error remained.)  I know Tomcats and HandyNotes are closely tied together in Retail, so maybe this may have caused a persistent error somehow upon initial install of HandyNotes.

**Comment by Nevcairiel** [comment]
HandyNotes does not cause that problem, and errors like that really aren't likely to be persistent. Its probably one addon causing it.

The problem is that the Classic map is typically fullscreen, its not meant to change size. So to enable it to change size, I have to override some stuff in the map. If another addon tries to do the same, but in a more incomplete manner, then the issue that you are seeing is the result of that.
