### ISSUE TITLE
Taint when reporting a player AFK in Battlegrounds (Classic)

### ISSUE THREAD

**Issue by clausjoergensen** [Nevcairiel/Mapster#23]
```
Global variable UIDROPDOWNMENU_MENU_LEVEL tainted by Mapster - Interface\FrameXML\UIDropDownMenu.lua:40
    securecall()
    Interface\FrameXML\UIDropDownMenu.lua:74 UIDropDownMenu_Initialize()
    Interface\AddOns\Blizzard_SharedMapDataProviders\GroupMembersDataProvider.lua:168
    xpcall()
    Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:759 WorldMapFrame:ProcessCanvasClickHandlers()
    Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:127
```

**Comment by clausjoergensen** [comment]
Can confirm the taint is caused by the RawHook of `WorldMapFrame.ScrollContainer.GetCursorPosition`. Implementation doesn't matter, any raw hook of the GetCursorPosition causes a taint when reporting people in BGs.

Root cause might very well be on Blizzards end.

**Comment by Nevcairiel** [comment]
That hook is unfortunately quite essential for what Mapster does, without that, in classic at least, all that would be possible would be the normal fullscreen map. Any change to its size requires adjusting the cursor size calculations otherwise clicked areas no longer match.

Hence, there isn't really anything I can do.
