### ISSUE TITLE
Classic Era button display issue

### ISSUE THREAD

**Issue by stierjon** [Nevcairiel/Mapster#85]
All other addons disabled, only mapster enabled. Seeing the mapster button off to the side of the map window on classic era. Same happens to the show questie button when that addon is enabled, so maybe blizz changed something about the map display that broke where these buttons go normally. See attached screenshot.
![mapster button](https://github.com/Nevcairiel/Mapster/assets/151063896/4deb531b-1f3c-4c50-a0dd-6ff5376baf35)

**Comment by Nevcairiel** [comment]
I have decided to discontinue classic support for Mapster.

Unlike many of my other mods, Mapster is designed to directly modify part of the Blizzard UI, and trying to keep up with the changes on 3 different versions of WoW is not a burden I want to put on myself, as I do not play any of the Classic variants.

I rather be clear about discontinuing support, instead of leaving it unclear to any users.
