### ISSUE TITLE
Map cannot move - Classic HC

### ISSUE THREAD

**Issue by Underoath50** [Nevcairiel/Mapster#87]
Unable to move the map now after patch 1.15.0. Running addon in Classic Hardcore

**Comment by Nevcairiel** [comment]
I have decided to discontinue classic support for Mapster.

Unlike many of my other mods, Mapster is designed to directly modify part of the Blizzard UI, and trying to keep up with the changes on 3 different versions of WoW is not a burden I want to put on myself, as I do not play any of the Classic variants.

I rather be clear about discontinuing support, instead of leaving it unclear to any users.
