### ISSUE TITLE
Addon doesn't work properly anymore in wow Era/HC ..

### ISSUE THREAD

**Issue by Eliran1991** [Nevcairiel/Mapster#88]
Addon doesn't work properly anymore in wow Era/HC ..

It seems the new blizzard map features they added pretty much broke down the addon, makes you unable to move or resize the map.

Are there any plans to update the addon? thanks!

**Comment by Nevcairiel** [comment]
I have decided to discontinue classic support for Mapster.

Unlike many of my other mods, Mapster is designed to directly modify part of the Blizzard UI, and trying to keep up with the changes on 3 different versions of WoW is not a burden I want to put on myself, as I do not play any of the Classic variants.

I rather be clear about discontinuing support, instead of leaving it unclear to any users.
